# fly.toml app configuration file generated for try-flame-autumn-field-6629 on 2023-12-17T11:13:13-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "try-flame"
primary_region = "atl"
kill_signal = "SIGINT"
kill_timeout = "5s"
swap_size_mb = 512

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "bluegreen"

[env]
  ECTO_IPV6 = "true"
  PHX_HOST = "try-flame.fly.dev"
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  [http_service.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "15s"
    method = "GET"
    path = "/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
